### ISSUE TITLE
Access article by url

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/mbk#18]
Link to article nr.3 here:
https://mbk-dev.netlify.app/nr-1-2021#at-male-verden
Redirects to:
https://mbk-dev.netlify.app/nr-1-2021#placeholder-article

**Comment by pwrstudio** [comment]
Does not seem to be working: 
https://bygningskunstogkultur.dk/nr-1-2021#lille-del-af-arkitekturen

**Comment by manegame** [comment]
Hey, could you give me the password please? Will look into this

**Comment by manegame** [comment]
I changed my approach a little bit. Now waiting for the browser to load everything before attempting nav. Works for me on Firefox, Brave (Chromium), and Safari

**Comment by pwrstudio** [comment]
Thanks! Password is: IBK2021
