### ISSUE TITLE
Menubar hidden by chrome navbar (android) 

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/mbk#19]
![Screenshot_20210128-172336_Chrome](https://user-images.githubusercontent.com/8209990/106172207-d618c880-6192-11eb-92c5-68b8029deb98.jpg)

**Comment by manegame** [comment]
Fix based on [this article](https://chanind.github.io/javascript/2019/09/28/avoid-100vh-on-mobile-web.html)
