### ISSUE TITLE
Scrolling in article text not working on mobile

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/mbk#21]
Or actually, also on desktop when below the mobile breakpoint. 
Only in Chrome. Although the scrolling is a bit weird on safari and firefox too...
There is some javascript manipulating the scroll right? In general would be better to not interfere with the normal scroll behaviour here.

**Comment by manegame** [comment]
Got this, it was indeed happening because of my code. I use it to prevent the slideshows from acting weirdly, blocking scrolls between articles. Now changed it to only run for bigger screens
