### ISSUE TITLE
Pass current active article as 'post' prop to set correct metadata 

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/mbk#29]
I am not sure how the currently active article is determined in the Articles component! 

https://github.com/pwrstudio/mbk/blob/2f7cf387b1c526b1e21ab0c48b0bc3d752042211/src/Components/Articles.svelte#L47

Around this line I would like to pass that article object to the MetaData component to set the current metadata.

Could you help me with this? @manegame 

thx

**Comment by manegame** [comment]
Hey Rasmus,

This should be fixed now. My approach is based on the active hash in our url.

1. Get the active hash or if it is `undefined,` set the 1st article hash
https://github.com/pwrstudio/mbk/blob/a4ab20805dc2e26d3ae16d089ad88ddb76001ab5/src/Routes/Single.svelte#L67
2. Set to the store
https://github.com/pwrstudio/mbk/blob/a4ab20805dc2e26d3ae16d089ad88ddb76001ab5/src/global.js#L28-L34
3. Create a derived store value, returning the currently active article
https://github.com/pwrstudio/mbk/blob/a4ab20805dc2e26d3ae16d089ad88ddb76001ab5/src/stores.js#L16-L22
4. We use this `$activeArticle` value inside the `MetaData` component

**Comment by pwrstudio** [comment]
thanks!
