### ISSUE TITLE
Check the finer points of the design against the PDF

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/mbk#6]
[Præsentation 2.pdf](https://github.com/pwrstudio/mbk/files/5835812/Praesentation.2.pdf)

**Comment by manegame** [comment]
Focused mostly on mobile things today. I think the UX of the menus should be good now. Could you have a look and lmk what you think?

**Comment by pwrstudio** [comment]
nice @manegame ! yes, looks good all around. I will have a closer look tomorrow, but looks pretty much done. The designer is sending tom feedback soon, but shouldn't be anything major. thx!
